name: Release

on:
  push:
    branches: [master]
env:
  GIT_USER_EMAIL: dante.aguilar41@gmail.com
  GIT_USER_NAME: danteay

jobs:
  bump:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.ACCESS_TOKEN }}'
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install -U commitizen

    - name: Create Bump
      run: |
        git config --local user.email "$GIT_USER_EMAIL"
        git config --local user.name "$GIT_USER_NAME"
        cz bump --changelog --yes

    - name: Push changes
      uses: Woile/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        tags: "true"